### ISSUE TITLE
Unable to install uzu on a newly installed Rakudo-Star

### ISSUE THREAD

**Issue by scmorrison** [scmorrison/uzu#1]
Gregor Goldbach @glauschwuffel wrote:
 
Hi there,
I’m unable to install Uzu. These are the steps I performed:
- Installed rakudo-star-2017-04
- Ran ```
zef install Uzu --depsonly
zef install Uzu
```

The last command fails with the following output:
```
$ zef install Uzu
===> Searching for: Uzu
===> Testing: Uzu:ver('0.1.8'):auth('gitlab:samcns')
t/00-basics.t .. ok 
===SORRY!===
Probable version skew in pre-compiled 'site#sources/279EEE655EA4F4F78AD74E7C34CB47AD9AE9A173 (Log::Any::Filter)' (cause: no object at index 1044)
t/01-serve.t ... No subtests run
===SORRY!===
Probable version skew in pre-compiled 'site#sources/279EEE655EA4F4F78AD74E7C34CB47AD9AE9A173 (Log::Any::Filter)' (cause: no object at index 1044)
t/02-build.t ... No subtests run
All tests successful.

Test Summary Report
-------------------
t/01-serve.t  (Wstat: 0 Tests: 0 Failed: 0)
  Parse errors: No plan found in TAP output
t/02-build.t  (Wstat: 0 Tests: 0 Failed: 0)
  Parse errors: No plan found in TAP output
Files=3, Tests=1,  1 wallclock secs
Result: FAILED
===> Testing [FAIL]: Uzu:ver('0.1.8'):auth('gitlab:samcns')
Aborting due to test failure: Uzu:ver('0.1.8'):auth('gitlab:samcns') (use --force to override)
  in code  at /Applications/Rakudo/share/perl6/site/sources/4B1D5A60B59D9541E13F76E0E2A2D550E0144053 (Zef::Client) line 346
  in method test at /Applications/Rakudo/share/perl6/site/sources/4B1D5A60B59D9541E13F76E0E2A2D550E0144053 (Zef::Client) line 325
  in code  at /Applications/Rakudo/share/perl6/site/sources/4B1D5A60B59D9541E13F76E0E2A2D550E0144053 (Zef::Client) line 497
  in sub  at /Applications/Rakudo/share/perl6/site/sources/4B1D5A60B59D9541E13F76E0E2A2D550E0144053 (Zef::Client) line 494
  in method install at /Applications/Rakudo/share/perl6/site/sources/4B1D5A60B59D9541E13F76E0E2A2D550E0144053 (Zef::Client) line 600
  in sub MAIN at /Applications/Rakudo/share/perl6/site/sources/09969B10D9F270B8DBAAB9961FA7E6CDB8AD58C9 (Zef::CLI) line 139
  in block <unit> at /Applications/Rakudo/share/perl6/site/resources/85BD232410222F167A35B9969B036802FECD78D2 line 1
```

I’m fairly new to Perl6 and zef, so I’m stuck at this point. Is there any information you need to resolve this issue?

**Comment by scmorrison** [comment]
Hi @glauschwuffel,

It does look like 2017.04 is the latest Rakudo Star release for MacOS. I have been testing using [rakudobrew](https://github.com/tadzik/rakudobrew) and having better success. It looks like `homebrew` has 2017.04 also. 

Can  you test again now that I have resolved the `zef` META6 author issue? 

Thanks again for the feedback / troubleshooting on the MacOS. This is very helpful.

Sam

**Comment by scmorrison** [comment]
Hi @glauschwuffel, 

Just a follow up. I was able to install using zef that comes installed with `brew install rakudo-star` using these commands:

```
zef install Uzu --depsonly --/test
zef install Uzu
```

There was a modification in rakudo in 2017.06 that caused an issue with IO / spawning processes.  Some of the tests that are failing on these dependencies run fine on the 2017.06 and later.

**Comment by glauschwuffel** [comment]
Hi @scmorrison,

sorry for the delay.

I'll try both: 2017-04 after your fix and 2017-06. This may take some time.

**Comment by glauschwuffel** [comment]
Hi @scmorrison ,

things are getting weirder. On my iMac the installation fails after a few seconds.

```
Gregors-iMac:~ glauschwuffel$ brew install rakudo-star
[...]
==> Pouring rakudo-star-2017.04.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/rakudo-star/2017.04: 1,117 files, 40.6MB
Gregors-iMac:~ glauschwuffel$ perl6 -v
This is Rakudo version 2017.04.3 built on MoarVM version 2017.04-53-g66c6dda
implementing Perl 6.c.
Gregors-iMac:~ glauschwuffel$ zef install Uzu --depsonly --/test
===> Searching for: Uzu
===> Searching for missing dependencies: Template6, Bailador:ver('0.0.6'), YAMLish, Test::Output
===> Failed to find dependencies: Bailador:ver('0.0.6')
Failed to find some required dependencies
  in block  at /usr/local/Cellar/rakudo-star/2017.04/share/perl6/site/sources/4B1D5A60B59D9541E13F76E0E2A2D550E0144053 (Zef::Client) line 142
  in block  at /usr/local/Cellar/rakudo-star/2017.04/share/perl6/site/sources/4B1D5A60B59D9541E13F76E0E2A2D550E0144053 (Zef::Client) line 100
  in sub MAIN at /usr/local/Cellar/rakudo-star/2017.04/share/perl6/site/sources/09969B10D9F270B8DBAAB9961FA7E6CDB8AD58C9 (Zef::CLI) line 124
  in block <unit> at /usr/local/Cellar/rakudo-star/2017.04/share/perl6/site/resources/85BD232410222F167A35B9969B036802FECD78D2 line 1
```

**Comment by scmorrison** [comment]
Hi @glauschwuffel 

ok, what happens when you run these commands?

```
zef install Uzu --deps-only --/test
zef install Uzu --/test
```

**Comment by glauschwuffel** [comment]
Hi @scmorrison ,

well, running the first command gets me these results:
````
Gregors-iMac:~ glauschwuffel$ zef install Uzu --depsonly --/test
===> Searching for: Uzu
===> Searching for missing dependencies: Template6, Bailador:ver('0.0.6'), YAMLish, Test::Output
===> Failed to find dependencies: Bailador:ver('0.0.6')
  in block  at /usr/local/Cellar/rakudo-star/2017.04/share/perl6/site/sources/4B1D5A60B59D9541E13F76E0E2A2D550E0144053 (Zef::Client) line 142
  in block  at /usr/local/Cellar/rakudo-star/2017.04/share/perl6/site/sources/4B1D5A60B59D9541E13F76E0E2A2D550E0144053 (Zef::Client) line 100
  in sub MAIN at /usr/local/Cellar/rakudo-star/2017.04/share/perl6/site/sources/09969B10D9F270B8DBAAB9961FA7E6CDB8AD58C9 (Zef::CLI) line 124
[...]
````

**Comment by scmorrison** [comment]
Ok, I have removed the Bailador version requirement from META6. Can you try that command again?

Also, I am still trying to track down the cause of these Log::Any issues:

```
Probable version skew in pre-compiled 'site#sources/279EEE655EA4F4F78AD74E7C34CB47AD9AE9A173 (Log::Any::Filter)' (cause: no object at index 1044)
```

**Comment by glauschwuffel** [comment]
Hi @scmorrison ,
I have been able to install the dependencies now. However, Uzu itself won't install because of the Log::Any issue:

````
Gregors-iMac:~ glauschwuffel$ zef install Uzu --/test
===> Searching for: Uzu
===> Installing: Uzu:ver('0.1.9')
===> Install [FAIL] for Uzu:ver('0.1.9'): ===SORRY!===
Probable version skew in pre-compiled 'site#sources/279EEE655EA4F4F78AD74E7C34CB47AD9AE9A173 (Log::Any::Filter)' (cause: no object at index 1044)
````

Should I try 2017-06 instead? And if so, where can I get a stable version of it?

**Comment by scmorrison** [comment]
Hi @glauschwuffel,

I have switched the web server to HTTP::Server::Tiny. Bailador is under heavy development at the moment so switching to a simple HTTP::Server::Tiny implementation for the time being. Uzu's web server requirements are much simpler than the features included with Bailador.

Please try these commands again:

```
zef update
zef install Uzu
```

Thanks,
Sam

**Comment by scmorrison** [comment]
> Should I try 2017-06 instead? And if so, where can I get a stable version of it?

The modifications that I changed should resolve the issue you were seeing (Log::Any is a Bailador dependency). But if you are interested in checking out the newest versions of rakudo, you can use [rakudobrew](https://github.com/tadzik/rakudobrew). It will allow you to install the latest versions. It compiles each version it installs, so it takes a little more time to setup than the official releases. 

Let me know if you have any questions about rakudobrew and I will try my best to provide assistance.

Thanks again,
Sam

**Comment by glauschwuffel** [comment]
Hi @scmorrison ,
the installation of HTTP::Server::Tiny fails. The test 06-channel.t fails:
````
===> Testing: HTTP::Server::Tiny:ver('0.0.1')
t/01-psgi.t ............. ok 
t/02-server.t ........... ok 
t/04-get.t .............. ok 
t/05-post.t ............. ok 
t/06-channel.t ..........1/2
# Failed test 'Received channel content as response from post request'
# at t/06-channel.t line 42
t/06-channel.t ..........2/2# expected: '123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899100'
#      got: ''
````

Can this module be installed on your machine?

**Comment by glauschwuffel** [comment]
Hi @scmorrison ,
I tried installed HTTP::Server::Tiny without running the tests (shame on me).

Installing Uzu still fails, this time with some other message:
````
Gebrauchtwarenzentrum:~ glauschwuffel$ zef install Uzu --/test
===> Searching for: Uzu
===> Installing: Uzu
===> Install [FAIL] for Uzu: ===SORRY!===
Could not find Log::Any at line 3 in:
    /Applications/Rakudo/share/perl6/site
    /Applications/Rakudo/share/perl6/vendor
    /Applications/Rakudo/share/perl6
    CompUnit::Repository::AbsolutePath<140626954585168>
    CompUnit::Repository::NQP<140626906879000>
    CompUnit::Repository::Perl5<140626906879040>
````

Is there some kind of cache I have to clear?

**Comment by scmorrison** [comment]
This looks like zef is still hanging onto the old version. This command should clear it out:

```
rm -rf ~/.zef/store/uzu.git ~/.zef/tmp/uzu.git
```

`~/.zef` is the default zef cache, but might be different on your system.

**Comment by scmorrison** [comment]
Also, I am seeing the `HTTP::Server::Tiny` test failure on 2017.04 OSX also. Install with this command:

```
zef install Uzu --/test
```

**Comment by glauschwuffel** [comment]
Hi @scmorrison ,

just a short update: I was able to install Uzu on 2017-06. Uzu still seems to use Bailador in some way:

````
uzu
===SORRY!===
Could not find Bailador at line 45 in:
    /Users/glauschwuffel/.perl6
    /Users/glauschwuffel/.rakudobrew/moar-2017.06/install/share/perl6/site
    /Users/glauschwuffel/.rakudobrew/moar-2017.06/install/share/perl6/vendor
    /Users/glauschwuffel/.rakudobrew/moar-2017.06/install/share/perl6
    CompUnit::Repository::AbsolutePath<140488928193360>
    CompUnit::Repository::NQP<140488945326816>
    CompUnit::Repository::Perl5<140488945326856>
````

I installed Bailador and the same error is reported. I'm still stuck, I'm afraid.

**Comment by scmorrison** [comment]
Hi @glauschwuffel,

This happens because zef caches these sometimes and doesn't update the cache with new versions. Try the following:

```
# Uninstall uzu
zef uninstall Uzu
# Clear the zef cache
rm -rf ~/.zef/store/uzu.git ~/.zef/tmp/uzu.git 
# Reinstall Uzu
zef install Uzu
# If that fails, try without tests
zef install Uzu --/test
```

Hope that works for you.

Thanks, 
Sam

**Comment by glauschwuffel** [comment]
Hi @scmorrison,

clearing the cache as described above didn't help, I had to remove the directories "store" and "tmp" completely.

I have successfully installed uzu now. Thanks for your support!

**Comment by scmorrison** [comment]
Great, glad you were able to get it installed. Please create more issues if you run into any problems or have questions.

Thanks, Sam
